# Microsoft - Windows Update Adoption and Performance Metrics

In [2]:
import pandas as pd  
import numpy as np  
import polars as pl
from datetime import date

In [3]:
df_update = pd.read_csv('../Data/008/fct_update_installations_2.csv', parse_dates=['installation_date'])

pl_update = pl.read_csv('../Data/008/fct_update_installations_2.csv', try_parse_dates=True)

# Pregunta 1

### En octubre de 2024, ¿cuál fue el tiempo de instalación más rápido registrado para una actualización de Windows que haya sido exitosa (sin errores)? Esta métrica nos ayudará a establecer un punto de referencia (benchmark) sobre el mejor rendimiento posible en nuestra estrategia de despliegue.

```SQL
SELECT
    MIN(installation_time_minutes) AS fastest_time
FROM fct_update_installations
WHERE ((EXTRACT (MONTH FROM installation_date) = 10) AND
      (EXTRACT (YEAR FROM installation_date) = 2024)) AND
    installation_error = FALSE;
```

In [12]:
oct = df_update[
    (df_update['installation_date'].dt.month == 10) &
    (df_update['installation_date'].dt.year == 2024) &
    (df_update['installation_error'] == False)
]

res = oct.agg(
    fastest_time = ('installation_time_minutes', 'min')
).T

In [11]:
res = pl_update.filter(
    (pl.col('installation_date').dt.month() == 10) &
    (pl.col('installation_date').dt.year() == 2024) &
    (pl.col('installation_error') == False)
).select(
    pl.col('installation_time_minutes').min().alias('fastest_time')
)

# Pregunta 2

### En noviembre de 2024, ¿cuántos usuarios únicos instalaron con éxito una actualización de Windows sin encontrar ningún error de instalación? Esta cifra nos ayudará a evaluar la confiabilidad de la actualización.

```SQL
SELECT
    COUNT(DISTINCT user_id)
FROM fct_update_installations
WHERE ((EXTRACT (MONTH FROM installation_date) = 11) AND
       (EXTRACT (YEAR FROM installation_date) = 2024)) AND
    installation_error = FALSE;
```

In [17]:
nov = df_update[
    (df_update['installation_date'].dt.month == 11) &
    (df_update['installation_date'].dt.year == 2024) &
    (df_update['installation_error'] == False)
]

res = nov.agg(
    tota_user_unique = ('user_id', 'nunique')
)

In [18]:
res = pl_update.filter(
    (pl.col('installation_date').dt.month() == 11) &
    (pl.col('installation_date').dt.year() == 2024) &
    (pl.col('installation_error') == False)
).select(
    pl.col('user_id').n_unique().alias('total_user_unique')
)

# Pregunta 3

### En diciembre de 2024, ¿cuál fue el tiempo de instalación más rápido para las actualizaciones de Windows entre los usuarios que no experimentaron ningún error? Esta métrica informará directamente nuestra estrategia de comunicación y despliegue para aumentar las tasas de adopción.

```SQL
SELECT
    MIN(installation_time_minutes) AS min_time_installation
FROM fct_update_installations
WHERE ((EXTRACT(MONTH FROM installation_date) = 12) AND
       (EXTRACT(YEAR FROM installation_date) = 2024)) AND
    installation_error = FALSE
```

In [19]:
dic = df_update[
    (df_update['installation_date'].dt.month == 12) &
    (df_update['installation_date'].dt.year == 2024) &
    (df_update['installation_error'] == False)
].reset_index()

res = dic.agg(
    min_time_installation = ('installation_time_minutes', 'min')
)

res

                       installation_time_minutes
min_time_installation                          4

In [20]:
res = pl_update.filter(
    (pl.col('installation_date').dt.month() == 12) &
    (pl.col('installation_date').dt.year() == 2024) &
    (pl.col('installation_error') == False)
).select(
    pl.col('installation_time_minutes').min().alias('min_time_installation')
)

res

shape: (1, 1)
┌───────────────────────┐
│ min_time_installation │
│ ---                   │
│ i64                   │
╞═══════════════════════╡
│ 4                     │
└───────────────────────┘